// Load modulesyyy

var Hapi = require('hapi');
var Db = require('../database');
var Utils = require('./utils');
/*
var HomeRoute = require('./routes/home');
var GeneralPageRoute = require('./routes/general-page');
var CatchAllRoute = require('./routes/catch-all');

var ClimaAuthCookie = require('../../clima-auth-cookie/lib/index.js');
*/



/*
*/
var ClimaApiTexts = require('../../clima-api-texts');

var Good = require("good");
var GoodConsole = require("good-console");
//var Version = require('./version');
//var Private = require('./private');


// Declare internals

var internals = {};


exports.init = function (port, next) {

    var server = new Hapi.Server();
    server.connection({ port: port });

    server.method([
        {
            name: "logStack",
            method: function(callsiteObj){

                var output = '\x1b[36m' + (callsiteObj.getFunctionName() || 'anonymous') + '()\x1b[90m in '
                            + callsiteObj.getFileName() + ":" + 
                            + callsiteObj.getLineNumber();

                server.log(["stack"], output);

                return output;
            },
            options: {
                callback: false
            }
        }
    ]);


    var plugins = [];

    // routes
    // plugins.push(HomeRoute);
    // plugins.push(GeneralPageRoute);
    // plugins.push(CatchAllRoute);

    // authentication
    //plugins.push(ClimaAuthCookie);

    plugins.push({
        register: Good,
        options: {
            reporters: [{
                reporter: GoodConsole,
                events: {
                    //ops: "*",
                    log: "*",  // maps to the "log" event 
                    response: "*",  // maps to either the "response" or "tail" event
                    error: "*",  // maps to the "request-error" event
                    request: "*"  // maps to the hapi 'request' event (generated by request.log())
                }
            }]
        }
    });

    plugins.push({
        register: ClimaApiTexts,
        options: {
            db: Db,
            utils: Utils
        }
    });

    server.register(plugins, function (err) {

        if (err) {
            return next(err);
        }

        server.start(function (err) {

            return next(err, server);
        });
    });




    // make sure we always have a "credentials" object on request.auth
    server.ext("onPostAuth", function(request, reply){
        request.auth.credentials = request.auth.credentials || {};
        return reply.continue();
    });

    // api
    // server.register(
    //     {
    //         register: ClimaApiTexts,
    //         options: {
    //             db: DB
    //         }
    //     },
    //     {
    //         routes: {
    //             prefix: "/api"
    //         }
    //     },
    //     function (err) {
    //         if (err) {
    //             return next(err);
    //         }
    //     }
    // );

};

